### ISSUE TITLE
Setup Swift SDK builds for Android

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#111]
We need to be able to build the Swift SDK (runtime, dispatch, foundation, xctest) for Android as a first step to supporting this platform.

Breakdown:
- [x] repair android and termux confusion
- [x] fix up android SDK selection
- [x] repair PIC code compilation when cross-compiling Windows -> Android
- [x] adjust SDK overlay for NDK changes
- [x] add a module map for Android NDK, allowing using C++ interop and Android NDK's libc++ from Swift: https://github.com/apple/swift/pull/72161/files
- [x] Support or workaround ICU cross-compilation
- [x] Update build.ps1 to support building the SDK for Android targets
  - [x] wire up platform information for individual builds
  - [x] enable NDK selection
  - [x] setup build environment
- [x] Create a GitHub Actions workflow to build Android SDKs: https://github.com/compnerd/swift-build/pull/740
- [x] enable support for building compiler-rt builtins for Android: https://github.com/swiftlang/swift/pull/74754
- [x] Swift C++ interop: fix cross-ref serialization ref: https://github.com/apple/swift/pull/72643

**Comment by hyp** [comment]
@compnerd I think we're done. Let's close?
