### ISSUE TITLE
`sourcekit-lsp` broken

### ISSUE THREAD

**Issue by chawyehsu** [thebrowsercompany/swift-build#115]
### Problem

sourcekit-lsp fails to start.

![image](https://github.com/thebrowsercompany/swift-build/assets/5764917/6ccab9d5-51f0-453c-ad8e-f26aa9f0aef2)

### Build info

build [20240302.0](https://github.com/thebrowsercompany/swift-build/releases/tag/20240302.0)

Note: I don't mean to expect support here since it's unofficial build and disclaimer of `with no expectation of support` has been claimed elsewhere. But I would raise issues I've found when trying these builds to see if someone also trying this and has the opportunity to resolve.

**Comment by chawyehsu** [comment]
don't know if it's related but in case, xref: https://github.com/apple/sourcekit-lsp/issues/1062

**Comment by compnerd** [comment]
This is a known issue and has been stated so on the forums before. You should try the latest builds as they contain a workaround in libdispatch which may be related.

**Comment by compnerd** [comment]
Wait, the xref and the screenshot are two separate issues - the former is something to do with the packaging. That belongs to apple/swift-installer-scripts.
