### ISSUE TITLE
[swift-build] Support arm64 swift-inspect in swift-toolchain.yml

### ISSUE THREAD

**Issue by kendalharland** [thebrowsercompany/swift-build#125]
This was previously failing. See [this build](https://github.com/thebrowsercompany/swift-build/actions/runs/8638316312/job/23682564936) for an example: The amd64 build succeeds while the arm64 build fails without an error message from `swift build …`. This will prevent us from including `swift-inspect` in the arm64 toolchain distribution until it is fixed.

**Comment by compnerd** [comment]
I think that we are using the wrong CMark and need the amd64 variant so that the compiler can run.
