### ISSUE TITLE
LLVM Content-Addressed Storage (CAS) support on Windows

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#155]

**Comment by hjyamauchi** [comment]
- [ ] Make the CAS unit tests (that pass on Mac) on Windows
- [ ] Make the ondisk CAS unit tests (that pass on Mac) on Windows
- [ ] Make the CAS tests (that pass on Mac) on Windows
- [ ] Make the ondisk CAS tests (that pass on Mac) on Windows
- [ ] Figure out how to setup the remote CAS test environment
- [ ] Make the remote CAS unit tests (that pass on Mac) on Windows
- [ ] Make the remote CAS tests (that pass on Mac) on Windows

**Comment by tristanlabelle** [comment]
Merged with #62 , which this was duplicating.
