### ISSUE TITLE
C++ interop

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#30]
C++ interop has been enabled in 5.9 and is likely going to play a larger role in the use of Swift in the compiler. Although we are closer to parity with recent improvements, exceptions and trivial types with non-trivial dtors are still unsupported. Getting to parity and then working on adding additional functional improvements like virtual method dispatch would simplify C++ interop usability for consumption of dependencies as well was enable Swift in the compiler.

**Comment by compnerd** [comment]
There is basically one item left for 5.9's C++ Interop support and the associated installer change that needs to be made before this is complete.  This will hopefully be completed this week.

**Comment by compnerd** [comment]
I'm going to go ahead and close this for now.  I think that the initial pass of the C++ Interop is now complete and the changes are in 5.9 as well.  There are a few disparities between Windows and the other platforms, but we should track those as individual issues on apple/swift.
