### ISSUE TITLE
Support Swift code in the compiler

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#32]
More and more parts of the Swift compiler are written in Swift and currently excluded from the Windows build. Supporting this will unblock new optimizations, regular expression support, new error diagnostics, and ensure that Swift on Windows evolves alongside other platforms, but it will require more space in CI could make build times longer.

**Comment by compnerd** [comment]
Swift Compiler Support is being built on Windows at this point even though there are some disabled pieces. I think that it makes sense to track those separately and mark this completed.
