### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#33]
Fix bad code generation issues and build hangs so that we can produce official ARM64 builds. This would unblock using Swift on Windows on Apple hardware via Parallels, which would be useful to macOS-based engineers at Apple and The Browser Company.

- [ ] Add cross-compile support to build.ps1
- [ ] Windows/ARM64 upstream swift CI/build up and running
- [ ] Fix the remaining ARM64 swift test failures

**Comment by tristanlabelle** [comment]
Some fixes thus far (in reverse chronological order):
- https://reviews.llvm.org/D155001
- https://github.com/apple/swift/pull/68174
- https://github.com/apple/swift/pull/67993
- https://github.com/apple/llvm-project/pull/7276
- https://github.com/apple/llvm-project/pull/7107
- https://github.com/apple/llvm-project/pull/7081

**Comment by hjyamauchi** [comment]
One more fix: https://github.com/llvm/llvm-project/commit/0ecd8846aedac1039448a32f87d299ce244dda68

**Comment by hjyamauchi** [comment]
https://github.com/llvm/llvm-project/commit/f776e0b6df611d973db1778256dfcd1dc37128c5

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/69836

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/69929

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/70050

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/69935

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/69368

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/69375

**Comment by hjyamauchi** [comment]
https://github.com/apple/swift/pull/68780

**Comment by tristanlabelle** [comment]
@hjyamauchi , with your work we are able to build and run arm64 now. Should we complete this and file more granular follow-ups like fixing tests?

**Comment by hjyamauchi** [comment]
Sure

**Comment by tristanlabelle** [comment]
@hjyamauchi  Ok, I'm completing this task because we do have arm64 support now. I don't know if the breakdown in the description is still valid but please file follow-up tasks as necessary.
