### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#35]
Docker images would provide a convenient means to perform CI operations on Windows. Additionally, customised docker images for toolchain development would provide a reproducible environment for building the toolchain which would simplify reproduction of CI failures.

- [x] swift 5.9.1
- [ ] swift 5.10
- [ ] swift main
- [ ] swift ci

**Comment by compnerd** [comment]
We have 5.9.1 docker images now!  We need to get 5.10 and main as well.

**Comment by compnerd** [comment]
https://github.com/apple/swift-docker/pull/366 should add the CI image.

**Comment by compnerd** [comment]
The docker images are not linked but can be generated. Some of the CI is already making use of it. I'm going to close this for now.
