### ISSUE TITLE
Build swift-inspect and swift-format in GitHub Actions

### ISSUE THREAD

**Issue by tristanlabelle** [thebrowsercompany/swift-build#91]

**Comment by kendalharland** [comment]
swift-inspect should be included in both the amd64 and arm64 releases of our private toolchain today.  I can confirm swift-inspect is present and executes in the amd64 release. I'll need to get someone working on arm64 to try it out

**Comment by kendalharland** [comment]
Confirmed that swift-inspect is also available on arm64. Closing this

**Comment by kendalharland** [comment]
In both releases it can be found by running this powershell command:

```powershell
& "$env:LOCALAPPDATA\Programs\Swift\Tools\0.0.0\swift-inspect.exe"
```
